---
version: 0.2

branches:
  feature/*, documentation/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*: 
    stage: pre-merge

stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/master
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: 'True'
          retryFetch: 'True'
          haltOnFailure: 'True'
      - ShellCommand:
          name: install dependencies
          command: npm install
      - ShellCommand:
          name: run lint
          command: npm run --silent lint -- --max-warnings 0
      - ShellCommand:
          name: run lint_md
          command: npm run --silent lint_md
      - ShellCommand:
          name: run test
          command: npm run test
      - ShellCommand:
          name: run coverage
          command: npm run coverage
